using GameServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GameServer.Host.Services;

internal static class TerrainModificationSchemaBootstrapper
{
    private const string TerrainModificationsCreateTableSql = """
CREATE TABLE IF NOT EXISTS \"TerrainModifications\" (
    \"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    \"CenterX\" real NOT NULL,
    \"CenterZ\" real NOT NULL,
    \"ChunkKey\" character varying(128) NULL,
    \"CreatedAt\" timestamp with time zone NOT NULL,
    \"LocationId\" bigint NOT NULL,
    \"MetadataJson\" jsonb NULL,
    \"ModificationType\" character varying(32) NOT NULL,
    \"ModifiedAtUtc\" timestamp with time zone NOT NULL,
    \"ModifiedBy\" uuid NULL,
    \"RadiusX\" real NOT NULL,
    \"RadiusZ\" real NOT NULL,
    \"SequenceTick\" bigint NOT NULL,
    \"TargetHeight\" real NOT NULL,
    \"UpdatedAt\" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS \"IX_TerrainModifications_LocationId\" ON \"TerrainModifications\" (\"LocationId\");
CREATE INDEX IF NOT EXISTS \"IX_TerrainModifications_LocationId_ChunkKey_SequenceTick\" ON \"TerrainModifications\" (\"LocationId\", \"ChunkKey\", \"SequenceTick\");
""";

    public static async Task EnsureCompatibleSchemaAsync(GameDbContext dbContext, ILogger logger, CancellationToken cancellationToken = default)
    {
        logger.LogInformation("TerrainModifications table creation SQL:\n{CreateSql}", TerrainModificationsCreateTableSql);

        string[] compatibilitySql =
        [
            "ALTER TABLE \"TerrainModifications\" ADD COLUMN IF NOT EXISTS \"ChunkKey\" character varying(128);",
            "ALTER TABLE \"TerrainModifications\" ADD COLUMN IF NOT EXISTS \"SequenceTick\" bigint NOT NULL DEFAULT 0;",
            "ALTER TABLE \"TerrainModifications\" ADD COLUMN IF NOT EXISTS \"MetadataJson\" jsonb NULL;",
            "ALTER TABLE \"TerrainModifications\" ADD COLUMN IF NOT EXISTS \"ModifiedAtUtc\" timestamp with time zone NOT NULL DEFAULT NOW();",
            "ALTER TABLE \"TerrainModifications\" ADD COLUMN IF NOT EXISTS \"ModifiedBy\" uuid NULL;",
            "CREATE SEQUENCE IF NOT EXISTS \"TerrainModifications_Id_seq\";",
            "ALTER TABLE \"TerrainModifications\" ALTER COLUMN \"Id\" SET DEFAULT nextval('\"TerrainModifications_Id_seq\"'::regclass);",
            "ALTER SEQUENCE \"TerrainModifications_Id_seq\" OWNED BY \"TerrainModifications\".\"Id\";",
            "SELECT setval('\"TerrainModifications_Id_seq\"', COALESCE((SELECT MAX(\"Id\") FROM \"TerrainModifications\"), 0) + 1, false);",
            "CREATE INDEX IF NOT EXISTS \"IX_TerrainModifications_LocationId\" ON \"TerrainModifications\" (\"LocationId\");",
            "CREATE INDEX IF NOT EXISTS \"IX_TerrainModifications_LocationId_ChunkKey_SequenceTick\" ON \"TerrainModifications\" (\"LocationId\", \"ChunkKey\", \"SequenceTick\");"
        ];

        foreach (string sql in compatibilitySql)
            await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
