// <auto-generated/>
// Polyfill for netstandard2.0 to support C# 9+ records and init-only properties.

// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
